DEBUG = True

DB_USERNAME = "root"
DB_PASSWORD = "5323128+1s"
DB_HOST = "127.0.0.1"
DB_PORT = "3306"
DB_NAME = "sbbs"

DB_URI = "mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8".format(DB_USERNAME, DB_PASSWORD, DB_HOST, DB_PORT, DB_NAME)

SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = False




